In [2]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [3]:
import numpy
n=numpy.arange(27)

In [4]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [6]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
import cv2

In [16]:
img=cv2.imread("smallgray.png",0)

In [17]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [18]:
cv2.imwrite("newsmallgrey.png",img)

True

In [20]:
img[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [21]:
for i in img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [22]:
for i in img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [24]:
ims=numpy.hstack((img,img))

In [25]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [28]:
lst=numpy.hsplit(ims,5)

In [29]:
lst

[array([[187, 158],
        [198, 125],
        [209, 134]], dtype=uint8),
 array([[104, 121],
        [255, 255],
        [255,  97]], dtype=uint8),
 array([[143, 187],
        [147, 198],
        [182, 209]], dtype=uint8),
 array([[158, 104],
        [125, 255],
        [134, 255]], dtype=uint8),
 array([[121, 143],
        [255, 147],
        [ 97, 182]], dtype=uint8)]